### ISSUE TITLE
Script also "fixes" commented out headers

### ISSUE THREAD

**Issue by ciscorucinski** [bryant1410/readmesfix#3]
Submitting on technicalities only.

Your script will also fix non-visible, commented-out headers ([see here](https://github.com/ciscorucinski/ChroMATERIAL/pull/28/files)).

This might still be desired just to catch all possible mistakes, but your pull request didn't have any visible changes to my users.

**Comment by bryant1410** [comment]
@ciscorucinski is it a concern? I would prefer to have my commented out headings fixed, even though my users don't see any visible change.

**Comment by ciscorucinski** [comment]
I don't disagree with you. Just posted in case you believe this might be something you want to fix or not - it's why I said I only posted due to technically (possible unintended feature)

**Comment by bryant1410** [comment]
Thanks! Will keep it, at least by now.
