### ISSUE TITLE
Thank you and this project may need a How-To-Do

### ISSUE THREAD

**Issue by Trinea** [bryant1410/readmesfix#5]
Hi bryant1410, Thank you for pull requests to fix my projects Markdown files.

I think this project can add a How-To-Do, so more user can use it, and save the users time also. for example:

#### 4. ...
and more.

Thank you.

**Comment by DaidoujiChen** [comment]
Hello @bryant1410,

Agree @Trinea, I need to fix a lot of repos. Thank you.

**Comment by bryant1410** [comment]
Done!
